name: 'jaffle_shop'               # project name
profile: 'dbt-fundamentals'       # profile to use in profiles.yml

# OPTIONAL VERSION CONFIGS
# version: 2
# config-version: '2.0.0'

# PATHS
model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analysis"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
function-paths: ["functions"]

# UNUSED PATHS
# osi-paths: ['osi']                      # Apache Ossie Semantic Layer Docs
# docs-paths: ['docs']                    # Optional: Custom place for doc blocks
# asset-paths: ['assets']                 # Optional: Files included here will be available in target/ when running dbt docs generate for documentation
# packages-install-path: ['packages']     # Optional: Custom Package Directory


clean-targets:                            # Specify a custom list of directories to be removed by the dbt clean command
    - "target"
    - "dbt_modules"
    - "dbt_packages"
    - "logs"


require-dbt-version: ">=2.0.0"            # Restricts project to only work with range of dbt versions (package control)

models:
  jaffle_shop:
    +database: analytics
    +meta:
        required_tests: {"unique.*|not_null": 1}
        required_docs: true

    staging:
        +schema: staging
        +materialized: view
        +static_analysis: strict
    intermediate:
        +schema: intermediate
        +materialized: table
        +static_analysis: strict
    marts:
        +schema: marts
        +materialized: table
        +static_analysis: strict

seeds:
  jaffle_shop:
    +schema: seeds

functions:
    jaffle_shop:
      +schema: functions

data_tests:
  +store_failures: true

unit_tests:
  +enabled: "{{ var('dbt_env', 'dev') != 'prod' }}"

flags:
  warn_error_options:
    error:
    warn:   
    silence:
      - PackageMissingProjectFile
      - UnusedResourceConfigPath
